### ISSUE TITLE
RDSNet is not in the detector registry

### ISSUE THREAD

**Issue by veryfocus** [wangsr126/RDSNet#1]
An error occurs when trying to run the quick demo:

loading annotations into memory...
Done (t=0.64s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 170, in main
    model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/cygdrive/u/zwxue/RDSNet-master/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/cygdrive/u/zwxue/RDSNet-master/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/cygdrive/u/zwxue/RDSNet-master/mmdetection/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'RDSNet is not in the detector registry

**Comment by wangsr126** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/issues/1061, and check whether 'recompile' helps.
