### ISSUE TITLE
OSError: torchvision://resnet101 is not a checkpoint file

### ISSUE THREAD

**Issue by gaihamxig** [wangsr126/RDSNet#2]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I try to train the model on a single gpu, an error occurred. can u help me figure it out?
**Reproduction**
1. What command or script did you run?

python tools/train.py configs/rdsnet/rdsnet_640_800_r101_fpn_2x.py 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?

**Environment**

**Error traceback**
2020-01-07 11:06:34,254 - INFO - Distributed training: False
2020-01-07 11:06:34,829 - INFO - load model from: torchvision://resnet101
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/data/home/t-mugai/RDSNet/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/data/home/t-mugai/RDSNet/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/data/home/t-mugai/RDSNet/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/data/home/t-mugai/RDSNet/mmdet/models/detectors/rdsnet.py", line 28, in __init__
    pretrained=pretrained)
  File "/data/home/t-mugai/RDSNet/mmdet/models/detectors/single_stage.py", line 26, in __init__
    self.init_weights(pretrained=pretrained)
  File "/data/home/t-mugai/RDSNet/mmdet/models/detectors/single_stage.py", line 30, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/data/home/t-mugai/RDSNet/mmdet/models/backbones/resnet.py", line 482, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/t-mugai/.conda/envs/gaimu_mmd/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 145, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: torchvision://resnet101 is not a checkpoint file

**Comment by wangsr126** [comment]
You may try to upgrade the version of mmcv. 
https://github.com/open-mmlab/mmcv/pull/89

**Comment by gaihamxig** [comment]
> You may try to upgrade the version of mmcv.
> open-mmlab/mmcv#89

thank you for your reply.
I tried to upgrade mmcv.
the [requirement.txt](https://github.com/wangsr126/RDSNet/blob/master/requirements.txt) says mmcv>=0.2.10. by now I have tried 0.2.10 and the newest 0.2.15. but with 0.2.15, there is another error.

so which version of mmcv did you use in this project?

thanks.

**Comment by wangsr126** [comment]
> > You may try to upgrade the version of mmcv.
> > [open-mmlab/mmcv#89](https://github.com/open-mmlab/mmcv/pull/89)
> 
> thank you for your reply.
> I tried to upgrade mmcv.
> the [requirement.txt](https://github.com/wangsr126/RDSNet/blob/master/requirements.txt) says mmcv>=0.2.10. by now I have tried 0.2.10 and the newest 0.2.15. but with 0.2.15, there is another error.
> 
> so which version of mmcv did you use in this project?
> 
> thanks.

The version I used is 0.2.13. And mmcv>=0.2.11 may solve the OSError.

**Comment by gaihamxig** [comment]
thanks
