### ISSUE TITLE
How to run RDS network on mm-detection 2.0

### ISSUE THREAD

**Issue by minan19605** [wangsr126/RDSNet#5]
Ubuntu 18.04, latest pytorch, Cuda 10.2

In this repo, mmdet part is old version.  If I install latest mm-detection, RDS network can't run.
If I don't install mm-detection,  when I try to pip install -e -v . in RDS directory, there has compile errors.

Then I try to add RDS model to mm-detection 2.0. I have one problem can't resolve:
In the anchor_target_with_mask_single(), this line have problem:
gt_masks = torch.from_numpy(gt_masks).float().to(bbox_targets.device)
Because the gt_masks is BitmapMasks format. it can't be from_numpy().

If I set configuration as:
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True, poly2mask=False),

Then there will have below errors. Could you please advise how to run RDS in mm-detection 2.0 or Run RDS base on your repo and don't depend on mm-detection?

2020-06-03 22:42:04,776 - mmdet - INFO - Start running, host: minan@DESKTOP-QFNNLBQ, work_dir: D:\code\mmdetection-master\work_dirs\rdsnet_refine_r101_fpn_1x
2020-06-03 22:42:04,777 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\reduction.py", line 51, in dumps
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "E:\Anaconda3\envs\keras\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

**Comment by minan19605** [comment]
For this issue, I found a method to fix it like below:

gt_masks = torch.from_numpy(**gt_masks.masks**).float().to(bbox_targets.device)

**Comment by jackweiwang** [comment]
can you shared you source code about mmdetection v2.0？， thanks

**Comment by minan19605** [comment]
this is my repo: 
https://github.com/minan19605/RDSNet

But I am not sure if it is fully correct.

**Comment by jackweiwang** [comment]
> this is my repo:
> https://github.com/minan19605/RDSNet
> 
> But I am not sure if it is fully correct.

thanks :)
